= RSpec/FactoryBot

== RSpec/FactoryBot/AttributeDefinedStatically

|===
| Enabled by default | Safe | Supports autocorrection | Version Added | Version Changed

| Enabled
| Yes
| Yes
| 1.28
| 2.0
|===

Always declare attribute values as blocks.

=== Examples

[source,ruby]
----
# bad
kind [:active, :rejected].sample

# good
kind { [:active, :rejected].sample }

# bad
closed_at 1.day.from_now

# good
closed_at { 1.day.from_now }

# bad
count 1

# good
count { 1 }
----

=== Configurable attributes

|===
| Name | Default value | Configurable values

| Include
| `spec/factories.rb`, `spec/factories/**/*.rb`, `features/support/factories/**/*.rb`
| Array
|===

=== References

* https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FactoryBot/AttributeDefinedStatically

== RSpec/FactoryBot/FactoryClassName

|===
| Enabled by default | Safe | Supports autocorrection | Version Added | Version Changed

| Enabled
| Yes
| Yes
| 1.37
| 2.0
|===

Use string value when setting the class attribute explicitly.

This cop would promote faster tests by lazy-loading of
application files. Also, this could help you suppress potential bugs
in combination with external libraries by avoiding a preload of
application files from the factory files.

=== Examples

[source,ruby]
----
# bad
factory :foo, class: Foo do
end

# good
factory :foo, class: 'Foo' do
end
----

=== Configurable attributes

|===
| Name | Default value | Configurable values

| Include
| `spec/factories.rb`, `spec/factories/**/*.rb`, `features/support/factories/**/*.rb`
| Array
|===

=== References

* https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FactoryBot/FactoryClassName

== RSpec/FactoryBot/MultipleInstances

|===
| Enabled by default | Safe | Supports autocorrection | Version Added | Version Changed

| Enabled
| Yes
| Yes
| 1.25
| <<next>>
|===

Checks for create_list usage.

This cop can be configured using the `EnforcedStyle` option

=== Examples

==== `EnforcedStyle: list` (default)

[source,ruby]
----
# bad
build_pair(:user)
3.times { build(:user) }
3.times { |n| create(:user, created_at: n.months.ago) }
create_pair(:user) do |user, n|
  user.created_at = n.months.ago
end

# good
build_list(:user, 2)
build_list(:user, 3)
create_list(:user, 3) do |user, n|
  user.created_at = n.months.ago
end
create_list(:user, 2) do |user, n|
  user.created_at = n.months.ago
end
----

==== `EnforcedStyle: list_and_pair`

[source,ruby]
----
# bad
2.times { build(:user) }
3.times { build(:user) }
2.times { |n| create(:user, created_at: n.months.ago) }
3.times { |n| create(:user, created_at: n.months.ago) }

# good
build_pair(:user)
build_list(:user, 3)
create_pair(:user) do |user, n|
  user.created_at = n.months.ago
end
create_list(:user, 3) do |user, n|
  user.created_at = n.months.ago
end
----

==== `EnforcedStyle: n_times`

[source,ruby]
----
# bad
build_pair(:user)
build_list(:user, 3)
create_pair(:user) do |user, n|
  user.created_at = n.months.ago
end
create_list(:user, 3) do |user, n|
  user.created_at = n.months.ago
end

# good
2.times { build(:user) }
3.times { build(:user) }
2.times { |n| create_pair(:user, user.created_at = n.months.ago) }
3.times { |n| create_pair(:user, user.created_at = n.months.ago) }
----

=== Configurable attributes

|===
| Name | Default value | Configurable values

| Include
| `+**/*_spec.rb+`, `+**/spec/**/*+`, `spec/factories.rb`, `spec/factories/**/*.rb`, `features/support/factories/**/*.rb`
| Array

| EnforcedStyle
| `list`
| `list`, `list_and_pair`, `n_times`
|===

=== References

* https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FactoryBot/MultipleInstances

== RSpec/FactoryBot/SyntaxMethods

|===
| Enabled by default | Safe | Supports autocorrection | Version Added | Version Changed

| Pending
| Yes
| Yes (Unsafe)
| <<next>>
| -
|===

Use shorthands from `FactoryBot::Syntax::Methods` in your specs.

=== Safety

The auto-correction is marked as unsafe because the cop
cannot verify whether you already include
`FactoryBot::Syntax::Methods` in your test suite.

If you're using Rails, add the following configuration to
`spec/support/factory_bot.rb` and be sure to require that file in
`rails_helper.rb`:

[source,ruby]
----
RSpec.configure do |config|
  config.include FactoryBot::Syntax::Methods
end
----

If you're not using Rails:

[source,ruby]
----
RSpec.configure do |config|
  config.include FactoryBot::Syntax::Methods

  config.before(:suite) do
    FactoryBot.find_definitions
  end
end
----

=== Examples

[source,ruby]
----
# bad
FactoryBot.create(:bar)
FactoryBot.build(:bar)
FactoryBot.attributes_for(:bar)

# good
create(:bar)
build(:bar)
attributes_for(:bar)
----

=== References

* https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FactoryBot/SyntaxMethods
